import type { PackageDetails } from "~/types"

export const goldPlanDetails: PackageDetails = {
  totalTests: 87,
  description:
    "This package includes 87 individual tests under 8 main categories",
  categories: [
    {
      id: crypto.randomUUID(),
      name: "Complete Blood Count",
      count: "24 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
        "PCT",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Diabetic",
      count: "1 Tests",
      features: ["Haemoglobin"],
    },
    {
      id: crypto.randomUUID(),
      name: "Kidney Function Tests",
      count: "7 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Lipid Profile",
      count: "9 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Liver Function Tests",
      count: "12 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Electrolytes",
      count: "3 Tests",
      features: ["Haemoglobin", "Total WBC Count", "Differential Count"],
    },
    {
      id: crypto.randomUUID(),
      name: "Bone Health",
      count: "2 Tests",
      features: ["Haemoglobin", "Total WBC Count"],
    },
    {
      id: crypto.randomUUID(),
      name: "Urine Complete Analysis",
      count: "20 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
      ],
    },
  ],
  orgPrice: "3299",
  disPrice: "2499",
  offerPercentage: "30",
  extraFeatures: [
    "79+ Tests Included",
    "Advanced Check",
    "NABL Certified Labs",
    "Report in 24 hrs",
  ],
}
