import type { PackageDetails } from "~/types"

export const signaturePlanDetails: PackageDetails = {
  totalTests: 97,
  description:
    "This package includes 97 individual tests under 14 main categories",
  categories: [
    {
      id: crypto.randomUUID(),
      name: "Complete Blood Count",
      count: "24 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
        "PCT",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Diabetic",
      count: "2 Tests",
      features: ["Haemoglobin", "Total WBC Count"],
    },
    {
      id: crypto.randomUUID(),
      name: "Kidney Function Tests",
      count: "7 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Lipid Profile",
      count: "9 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Liver Function Tests",
      count: "12 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Electrolytes",
      count: "3 Tests",
      features: ["Haemoglobin", "Total WBC Count", "Differential Count"],
    },
    {
      id: crypto.randomUUID(),
      name: "Bone Health",
      count: "2 Tests",
      features: ["Haemoglobin", "Total WBC Count"],
    },
    {
      id: crypto.randomUUID(),
      name: "Thyroid Function Tests",
      count: "3 Tests",
      features: ["Neutrophils", "Lymphocytes", "Eosinophils"],
    },
    {
      id: crypto.randomUUID(),
      name: "Tumor Marker",
      count: "1 Tests",
      features: ["Monocytes"],
    },
    {
      id: crypto.randomUUID(),
      name: "Vitamins",
      count: "2 Tests",
      features: ["Lymphocytes", "Eosinophils"],
    },
    {
      id: crypto.randomUUID(),
      name: "Iron Profile",
      count: "4 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Urine Complete Analysis",
      count: "20 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
        "PCT",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Pancreas profile",
      count: "2 Tests",
      features: ["Monocytes", "Basophils"],
    },
    {
      id: crypto.randomUUID(),
      name: "Cardiac panel",
      count: "6 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
      ],
    },
  ],
  orgPrice: "3999",
  disPrice: "5299",
  offerPercentage: "30",
  extraFeatures: [
    "85+ Tests Included",
    "Full Body Master",
    "NABL Certified Labs",
    "Report in 24 hrs",
  ],
}
