import type { PackageDetails } from "~/types"

export const silverPlanDetails: PackageDetails = {
  totalTests: 61,
  description:
    "This package includes 61 individual tests under 5 main categories",
  categories: [
    {
      id: crypto.randomUUID(),
      name: "Complete Blood Count",
      count: "24 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
        "PCT",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Diabetic",
      count: "1 Tests",
      features: ["Haemoglobin"],
    },
    {
      id: crypto.randomUUID(),
      name: "Kidney Function Tests",
      count: "7 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Lipid Profile",
      count: "9 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
      ],
    },
    {
      id: crypto.randomUUID(),
      name: "Urine Complete Analysis",
      count: "20 Tests",
      features: [
        "Haemoglobin",
        "Total WBC Count",
        "Differential Count",
        "Neutrophils",
        "Lymphocytes",
        "Eosinophils",
        "Monocytes",
        "Basophils",
        "PCV",
        "RBC",
        "MCV",
        "MCH",
        "Platelet Count",
        "Absolute Neutrophil Count",
        "Absolute Lymphocyte Count",
        "Absolute Eosinophil Count",
        "Absolute Monocyte Count",
        "Absolute Basophil Count",
        "RDW-CV",
        "RDW-SD",
        "PDW MPV",
        "P-LCR",
      ],
    },
  ],
  orgPrice: "1599",
  disPrice: "1199",
  offerPercentage: "30",
  extraFeatures: [
    "60+ Tests Included",
    "Essential Check",
    "NABL Certified Labs",
    "Report in 24 hrs",
  ],
}
